FORMAT: 1A
HOST: http://oraclearena.apiblueprint.org/

# Oracle Arena Beer API

Oracle Arena is a simple API allowing allowing to the Beer providers in Oracle 

## Questions Collection [/beers]

### List All Questions [GET]

We list all questions and votes for a particular beer.

+ Response 200 (application/json)

        [
            {
                "question": "What are your favorite beers",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Blatz",
                        "votes": 2048
                    }, {
                        "choice": "Miller",
                        "votes": 1024
                    }, {
                        "choice": "Schlitz",
                        "votes": 512
                    }, {
                        "choice": "Old Milwaukee",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question about Beer  [POST]

You may create your own question about beer using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Blatz",
                "Miller",
                "Schlitz",
                "Old Milwaukee"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "What is your favoite beer?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Blatz",
                        "votes": 0
                    }, {
                        "choice": "Miller",
                        "votes": 0
                    }, {
                        "choice": "Miller",
                        "votes": 0
                    }, {
                        "choice": "Old Milwaukee",
                        "votes": 0
                    }
                ]
            }

### Get the votes for a specific beer [GET]
Returns all vote counts for a specific Beer


+ Parameters
    + beer:1000 (number) - Beer number.

+ Response 200 (application/json)

        [
            { 
                "name": "Blatz",
                "accountid": "1000",                
                "votes": "2048",
            }    
        ]